### ISSUE TITLE
huginn teamplay

### ISSUE THREAD

**Issue by Matthias84** [biotinker/LibreTasks#198]
Huginn is a selfhosting service that is similar  to LT and receives events and triggers actions. They are looking for [a mobile client](https://github.com/cantino/huginn/issues/166). Maybe LT can fill this gap and trigger events also on server-side?

**Comment by biotinker** [comment]
I don't think this is a good choice for their project- the sorts of things we do are similar, yes, but the content is extremely different. LibreTasks has no way whatsoever to interface with a server-side anything at the moment. They're probably better off writing their own app. Presumably their app would just be an interface to control their server-side actions and triggers, anyway, rather than setting up actions and triggers within the android system like LibreTasks does.

Thanks for the suggestion though!
